# Generated by Django 3.0.8 on 2020-09-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20200705_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='eventmember',
            table='eventember',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='user',
        ),
    ]
