# Generated by Django 3.0.8 on 2020-09-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20200908_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
